# ╭─────────────────────────────────────────────────────────╮
# │                    Yazi Theme Config                    │
# ╰─────────────────────────────────────────────────────────╯

# ═══════════════════════════════════════════════════════════
#  Theme Selection
# ═══════════════════════════════════════════════════════════

[flavor]
use = "dracula"
